import type { Metadata } from "next";
import { SidebarInset, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar";
import { Separator } from "@/components/ui/separator";
import { UserNav } from "@/components/dashboard/user-nav"
import { cookies } from "next/headers"
import React from "react";
import { PathCrumbs } from "@/components/dashboard/path-crumbs";

export const metadata: Metadata = {
  title: "Dashboard | Intellicord",
  description: "Generated by create next app",
};

export default async function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const discord_avatar_cookie = cookieStore.get("discord_avatar")?.value;
  const discord_avatar = discord_avatar_cookie ? decodeURI(discord_avatar_cookie) : "test.png"
  const discord_username = cookieStore.get("discord_username")?.value || "";
  
  return (
    <SidebarProvider>
      <AppSidebar />
      <SidebarInset>
        <header className="flex h-16 shrink-0 items-center justify-between gap-2 border-b px-4">
          <div className="flex items-center gap-2">
          <SidebarTrigger className="-ml-1" />
          <Separator orientation="vertical" className="mr-2 h-4" />
          <PathCrumbs />
          </div>
          <UserNav avatar={discord_avatar} username={discord_username}/>
        </header>
        <main className="flex-1">
          <div className="p-4">
            {children}
          </div>
        </main>
      </SidebarInset>
    </SidebarProvider>
  );
}
